### ISSUE TITLE
Unable to run setup person

### ISSUE THREAD

**Issue by treydock** [hamano/lb#5]
I get similar error with add subcommand.

```
# /users/sysp/tdockendorf/git/lb/lb setup person -D 'cn=ldap-admin,<OMIT>' -w '<OMIT>' -b 'ou=bench,<OMIT>' --cn 'user%d' --last 10000 ldap://localhost/
This is LDAPBench, Version 0.9.3
Copyright 2015 Open Source Solution Technology Corporation
This software is released under the MIT License.

Adding person entry: cn=user1,ou=bench,<OMIT>
panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 1 [running]:
github.com/hamano/golang-openldap.(*Ldap).doModify.func4(0xc42001ad20, 0x5, 0x5, 0x220c880, 0x220c9e0, 0xc42001ad20, 0xc420048850)
        /users/sysp/tdockendorf/go/src/github.com/hamano/golang-openldap/add-modify-delete.go:115 +0x100
github.com/hamano/golang-openldap.(*Ldap).doModify(0xc42000e050, 0xc42000cb40, 0x1f, 0xc42001acf0, 0x0, 0xc420048901, 0x0)
        /users/sysp/tdockendorf/go/src/github.com/hamano/golang-openldap/add-modify-delete.go:115 +0x40e
github.com/hamano/golang-openldap.(*Ldap).Add(0xc42000e050, 0xc42000cb40, 0x1f, 0xc42001acf0, 0x1, 0x35)
        /users/sysp/tdockendorf/go/src/github.com/hamano/golang-openldap/add-modify-delete.go:165 +0x75
main.setupPersonOne(0xc420086420, 0xc42000e050, 0xc420014e30, 0x5, 0x1, 0xc420014e30)
        /users/sysp/tdockendorf/git/lb/setup.go:115 +0x58a
main.setupPerson(0xc420086420, 0x56cf80, 0xc420014df0)
        /users/sysp/tdockendorf/git/lb/setup.go:89 +0x4a6
github.com/urfave/cli.HandleAction(0x574340, 0x5b0cc0, 0xc420086420, 0x0, 0xc420070300)
        /users/sysp/tdockendorf/go/src/github.com/urfave/cli/app.go:501 +0xd4
github.com/urfave/cli.Command.Run(0x5a65b8, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x5a7ebf, 0xe, 0x0, ...)
        /users/sysp/tdockendorf/go/src/github.com/urfave/cli/command.go:165 +0x54d
github.com/urfave/cli.(*App).RunAsSubcommand(0xc4200981c0, 0xc420086160, 0x0, 0x0)
        /users/sysp/tdockendorf/go/src/github.com/urfave/cli/app.go:383 +0xb28
github.com/urfave/cli.Command.startApp(0x5a6387, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x5a8934, 0x11, 0x0, ...)
        /users/sysp/tdockendorf/go/src/github.com/urfave/cli/command.go:329 +0x8fa
github.com/urfave/cli.Command.Run(0x5a6387, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x5a8934, 0x11, 0x0, ...)
        /users/sysp/tdockendorf/go/src/github.com/urfave/cli/command.go:103 +0x960
github.com/urfave/cli.(*App).Run(0xc420098000, 0xc4200100e0, 0xe, 0xe, 0x0, 0x0)
        /users/sysp/tdockendorf/go/src/github.com/urfave/cli/app.go:259 +0x7b7
main.main()
        /users/sysp/tdockendorf/git/lb/lb.go:280 +0x9aa
```

**Comment by hamano** [comment]
you need to set GODEBUG to build old lb. see old README:
~~~
$ export GODEBUG=cgocheck=0
~~~

but now I rewrite the code without cgo, so this issue was resolved completely.
thank you.
